# Reusable workflow for all Linux builds
name: Fuse App For Linux
run-name: Build Fuse App for Linux / ${{ github.actor }} /

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      dependencies:
        type: string
        required: false
        default: ""
      configure_params:
        type: string
        required: false
        default: ""
      verify_ui:
        type: string
        required: true
      verify_audio:
        type: string
        required: false
        default: "oss"
      verify_other:
        type: string
        required: false
        default: ""

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: bash
    steps:
      - name: (1) Install dependencies
        if: ${{ inputs.dependencies }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ inputs.dependencies }}

      - name: (2) Check out repository code
        uses: actions/checkout@v3

      - name: (3) Download libspectrum artefact
        uses: actions/download-artifact@v3
        with:
          name: libspectrum-compiled-linux
          path: libspectrum

      - name: (4) Install libspectrum from artefact
        run: |
          cd libspectrum
          tar -xvf libspectrum-compiled-linux.tar
          sudo make install-strip
          cd ..
          echo "Done"

      - name: (5) Autogen.sh
        run: ./autogen.sh

      - name: (6) Configure for Linux
        run: |
          ./configure ${{ inputs.configure_params }} \
          |& tee ./configure.out

      - name: (7) Verify output from configure
        # Most of the tested strings are common for all Linux builds
        # Only the strings related to UI selection differ
        run: |          
          .github/scripts/in_config.sh "Fuse options"
          .github/scripts/in_config.sh "zlib support: yes"
          .github/scripts/in_config.sh "libxml2 support: yes"
          .github/scripts/in_config.sh "libpng support: yes"
          .github/scripts/in_config.sh "Spectranet support: yes"
          .github/scripts/in_config.sh "SpeccyBoot support: yes"
          .github/scripts/in_config.sh "TTX2000 S support: yes"
          .github/scripts/in_config.sh "Desktop integration: no"
          
          .github/scripts/in_config.sh "User interface: ${{ inputs.verify_ui }}"
          .github/scripts/in_config.sh "Selected audio driver: ${{ inputs.verify_audio }}"
      - if: ${{ inputs.verify_other }}
        run: |
          .github/scripts/in_config.sh "${{ inputs.verify_other }}"

      - name: (7) Make
        run: make

      - name: (8) Install
        run: sudo make install

      - name: (9) Finish
        run: |
          echo "üçè Finishing with status ${{ job.status }}."
